Repository SeSAC-Ermes/Epari-serverless, pull requests merged in 2024-12, with the labels that each got.

#1 [REFACTOR] 최신 데이터 저장 로직 개선
  Epari-admin/backend/admin-courses-collector.mjs
  Epari-admin/frontend/dashboard-admin-courses.html
  Epari-admin/frontend/dashboard-admin-courses.mjs
Labels: refactoring

#2 [FEAT] 강의 운영현황 및 강의실 사용 현황 차트 구현
  Epari-admin/backend/admin-collectors.mjs
  Epari-admin/backend/admin-courses-collector.mjs
  Epari-admin/backend/admin-facility-collector.mjs
  Epari-admin/frontend/dashboard-admin-courses.css
  Epari-admin/frontend/dashboard-admin-courses.html
  Epari-admin/frontend/dashboard-admin-courses.mjs
  Epari-admin/package-lock.json
  Epari-admin/package.json
Labels: enhancement

#5 [FEAT] 강의 선호도 차트
  Epari-admin/express.mjs
  Epari-admin/public/dashboard-admin-courses.html
  Epari-admin/public/dashboard-admin-courses.mjs
  Epari-admin/src/collectors/admin-collectors.mjs
  Epari-admin/src/collectors/admin-preference-collector.mjs
  package-lock.json
Labels: enhancement

#6 [FEAT] admin 페이지 layout 변경
  Epari-admin/public/dashboard-admin-courses.css
  Epari-admin/public/dashboard-admin-courses.html
  Epari-admin/public/dashboard-admin-courses.mjs
  Epari-admin/src/collectors/admin-facility-collector.mjs
Labels: enhancement

#7 [FEAT] 강의 분야별 선호도의 트렌드가 데이터에 따라 변동하도록 구현
  Epari-admin/public/dashboard-admin-courses.mjs
  Epari-admin/src/collectors/admin-preference-collector.mjs
Labels: enhancement

#9 [FEAT] 선호도 json 데이터에 color 저장되지 않도록 수정
  Epari-admin/src/collectors/admin-preference-collector.mjs
Labels: bug

#11 [FEAT] DynamoDB 연동 로직 추가
  Epari-admin/express.mjs
  Epari-admin/public/dashboard-admin.mjs
  Epari-admin/src/collectors/admin-courses-collector.mjs
  Epari-admin/src/collectors/admin-facility-collector.mjs
  Epari-admin/src/collectors/admin-performance-collector.mjs
  Epari-admin/src/collectors/admin-visitors-collector.mjs
  Epari-admin/src/utils/dynamodb-utils.mjs
  package-lock.json
  package.json
Labels: enhancement

#13 [FEAT] 강사 대시보드 관련 기능 구현
  Epari-admin/frontend/dashboard-admin-courses.js
  Epari-instructor/.gitignore
  Epari-instructor/.gitkeep
  Epari-instructor/backend/instructor-assignment-status-collector.js
  Epari-instructor/backend/instructor-current-assignment-status-collector.js
  Epari-instructor/backend/instructor-exam-status-collector.js
  Epari-instructor/backend/instructor-students-status-collector.js
  Epari-instructor/backend/instructor-weekly-scores-statistics-collector.js
  Epari-instructor/backend/package-lock.json
  Epari-instructor/backend/package.json
  Epari-instructor/backend/src/index.js
  Epari-instructor/backend/utils/s3-loader.js
  Epari-instructor/backend/utils/s3-uploader.js
  Epari-instructor/backend/utils/statistics-repository.js
  Epari-instructor/frontend/dashboard-instructor.css
  Epari-instructor/frontend/dashboard-instructor.html
  Epari-instructor/frontend/js/dashboard-instructor-assignment.js
  Epari-instructor/frontend/js/dashboard-instructor-current-assignment.js
  Epari-instructor/frontend/js/dashboard-instructor-exam.js
  Epari-instructor/frontend/js/dashboard-instructor-students.js
  Epari-instructor/frontend/js/dashboard-instructor-weekly-scores.js
  Epari-instructor/package-lock.json
  Epari-instructor/package.json
Labels: enhancement

#14 [REFACTOR] admin collector에 로컬 스토리지 저장 로직 삭제
  Epari-admin/src/collectors/admin-courses-collector.mjs
  Epari-admin/src/collectors/admin-preference-collector.mjs
  Epari-admin/src/collectors/admin-student-pages-collector.mjs
  Epari-admin/src/collectors/admin-visitors-collector.mjs
Labels: refactoring

#15 [FEAT] 게시판 업데이트
  Epari-board/dynamodb-table.json
  Epari-board/index.html
  Epari-board/package-lock.json
  Epari-board/package.json
  Epari-board/server/index.mjs
  Epari-board/server/routes/carbon.mjs
  Epari-board/server/routes/posts.mjs
  Epari-board/server/temp/b2622ba0-72ed-4ab3-8b1d-880a858f497c-x8NGXO0zBc.png
  Epari-board/server/temp/b2622ba0-72ed-4ab3-8b1d-880a858f497c.txt
  Epari-board/src/App.jsx
  Epari-board/src/assets/Athena.svg
  Epari-board/src/assets/EMR.svg
  Epari-board/src/assets/Glue.svg
  Epari-board/src/assets/default-avatar.png
  Epari-board/src/components/chart/D3ChartPlugin.js
  Epari-board/src/components/chart/D3Editor.jsx
  Epari-board/src/components/chart/D3PieChart.jsx
  Epari-board/src/components/comment/CommentItem.jsx
  Epari-board/src/components/editor/D3Editor.jsx
  Epari-board/src/components/editor/EditorTabs.jsx
  Epari-board/src/components/editor/TinyEditor.jsx
  Epari-board/src/components/editor/ToastEditor.jsx
  Epari-board/src/components/layout/Layout.jsx
  Epari-board/src/components/layout/Sidebar.jsx
  Epari-board/src/components/post/CategoryFilter.jsx
  Epari-board/src/components/post/PostCard.jsx
  Epari-board/src/components/post/TagSearch.jsx
  Epari-board/src/index.css
  Epari-board/src/main.jsx
  Epari-board/src/pages/ChartEditorPage.jsx
  Epari-board/src/pages/HomePage.jsx
  Epari-board/src/pages/PostDetailPage.jsx
  Epari-board/src/pages/WritePostPage.jsx
  Epari-board/src/styles/editor.css
  Epari-board/tailwind.config.js
  Epari-board/vite.config.js
Labels: enhancement
